apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubectl apply -k deploy/k8s
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/vivianludrick/preview
    newTag: latest
